name: Auto News Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch News
        run: curl -o news.json https://criclive24-99787-default-rtdb.firebaseio.com/news.json

      - name: Generate Pages
        run: |
          mkdir -p news

          for row in $(cat news.json | jq -c 'to_entries[]'); do

            title=$(echo $row | jq -r '.value.title')
            content=$(echo $row | jq -r '.value.content')
            image=$(echo $row | jq -r '.value.image')
            date=$(echo $row | jq -r '.value.time')

            slug=$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')

            echo "<h1>$title</h1><p>$content</p>" > news/$slug.html

          done

      - name: Commit & Push
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"

          git add .
          git commit -m "Auto news pages" || echo "no change"
          git push
