name: Auto News Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch News
        run: curl -o news.json https://criclive24-99787-default-rtdb.firebaseio.com/news.json

      - name: Check JSON
        run: cat news.json

      - name: Generate Pages
        run: |
          mkdir -p news
          template=$(cat template/news-template.html)

          count=$(cat news.json | jq '. | length')

          if [ "$count" = "null" ]; then
            echo "No data found ❌"
            exit 0
          fi

          for i in $(seq 0 $(($count-1))); do
            row=$(cat news.json | jq -c ".[$i]")

            title=$(echo $row | jq -r '.title')
            content=$(echo $row | jq -r '.content')
            image=$(echo $row | jq -r '.image')
            date=$(echo $row | jq -r '.time')

            slug=$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')

            page="$template"

            page="${page//\{\{TITLE\}\}/$title}"
            page="${page//\{\{CONTENT\}\}/$content}"

            echo "$page" > news/$slug.html
          done

      - name: Commit
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"

          git add .
          git commit -m "update" || echo "no change"
          git push
